name: Meshsync
on:
  push:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    # * Matches zero or more characters, but does not match the / character
    # ** Matches zero or more of any character
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Setup go
        uses: actions/setup-go@main
        with:
          check-latest: 'true'
          go-version: '^1.19'
      - name: Build check
        run: GOPROXY=direct GOSUMDB=off GO111MODULE=on go build -o meshery-meshsync . 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52
          args:  --exclude=G107 --timeout=10m ./...

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
          skip-build-cache: true
